### ISSUE TITLE
Data using different time intervals

### ISSUE THREAD

**Issue by mikahpinegar** [TUW-GEO/flagit#4]
How things are setup now, the data needs to be hourly. We have data that is sampled every 15 minutes, I would like to pass in a parameter called `frequency` in hours and use that to calculate the number of samples that make up an hour. I tried using pd.infer_freq() but it wasn't reliable at guessing the frequency so i would like to calculate it on my own or use the fact that a dataset is sampled every x hours and then pass it in to your module.

This would then be used to dynamically scale windows etc, instead of just assuming that 12 samples is 12 hours. 

I'll be working on this in the next few weeks and may raise a PR if that is a feature you would like to add.

In the previous issue I opened you said you were working on a new version. What features are you planning on adding? I don't want to implement something you're already working on but we're very excited to get this package working for our dataset! 

Thanks again :)

**Comment by daberer** [comment]
Sure that sounds like a very useful feature, thanks! We are of course glad to add it as an option when its done. 
I experimented a bit with pd.infer_freq() myself (to check if the input is indeed hourly), but like you I found it was not reliable in my case either.

The new version probably will not have many new features. Mainly we are adapting it so we can use it internally in our processing chain and fix a few bugs in the process (see [develop branch](https://github.com/TUW-GEO/flagit/tree/develop)).

Many thanks!

**Comment by mikahpinegar** [comment]
Ok great! 

Alternatively I've written some code to more accurately infer the frequency if that's something you'd like to add to the module as well. Right now I have it in a separate file that's doing preprocessing on our data but it may be useful to build in as a method for your class.

We could add a column to the `data` dataframe that are timestamps and use that to calculate the interval. 

Maybe the most robust solution is to do both. So having a parameter called frequency that the user can pass in that defaults to `None`, if that is `None` then call a method called `infer_freq(data)` if that returns None (because there is no timestamp column in `data`) then assume hourly data.

What do you think?

**Comment by daberer** [comment]
A function or method that can infer the frequency would be super helpful.

so the way I thought people would use this package is by using timestamps as index (see picture below from our [documentation](https://flagit.readthedocs.io/en/latest/)):
![image](https://user-images.githubusercontent.com/47424802/154706306-83b6e645-259a-4390-83f6-731c46503304.png)

in any case, the solution that by default it assumes hourly data sounds good to me :)

**Comment by mikahpinegar** [comment]
Ah ok, I was a bit confused by that but it makes perfect sense. 

So then I'll just have it call `infer_freq(data)` and then use the index column which will be timestamps and return the frequency in hours, if the index is not timestamps should I cause an exception due to incorrectly formatted data or let it still run without knowing the time interval? Can I add somewhere in either the README or a comment an example table of data? I was unclear that the index should be timestamps when getting started. 

Also, I noticed you're adding sensor depth as a param on develop. This is something that would be very helpful for us because our experiment has multiple depths. When do you anticipate merging `develop` and how stable is it now? I would love to be able to use the depths for our data.

**Comment by daberer** [comment]
maybe raise a warning instead of an exception?

Come to think of it, there will not be much to add that's not in the develop branch already. Think I can probably merge by the end of next week or within 2 weeks at the latest. Think it runs okay (there are some issues for python versions above 3.6).

The sensor_depths variables were added because at ISMN we use the D04 and D05 flag (rise in soil moisture without precipitation event) only for surface soil moisture timeseries (depth <= 10cm). For these two flags additional ancillary precipitation data is required as input. 

Therefore the depth I added to the code will only affect results if you provide additional precipitation data in the input dataframe. Probably not helpful for your application I think.

For the README, maybe we could do something like an ipython notebook instruction?

**Comment by mikahpinegar** [comment]
Ok yeah, that won't effect our dataset then because we don't collect precipitation data. In the future we might build out an application to fetch rainfall data using latitude and longitude from some API but for now that's not the case.

I'll talk with my team today about what our timeline is but I may just wait until you merge `develop` into `master` so I don't have to worry about resolving merge conflicts or anything. 

I like the idea of using a notebook, that seems like a great idea. I'll add that to the PR I make and you can let me know if I should add anything to it during the review process.

**Comment by mikahpinegar** [comment]
I have a questions about when the `window` is `25` for the rolling calculations. If I'm generalizing to use different frequencies would I do `24 * nunber_of_samples_in_an_hour + 1` or `25 * nunber_of_samples_in_an_hour`? i'm unclear if you're trying to get the center sample of a 24 hour period or if you're trying to sample 25 hours. This is an example line https://github.com/TUW-GEO/flagit/blob/f7201a8c9b6f6a05cbfcfc54df162ac08a2b33fb/src/flagit/flagit.py#L349

Also, when you're doing shifts, that will also need to be multiplied by the number of samples in an hour correct? An example line is below. 
https://github.com/TUW-GEO/flagit/blob/f7201a8c9b6f6a05cbfcfc54df162ac08a2b33fb/src/flagit/flagit.py#L438

Thanks for the help! I'm new to using python as a statistical tool so I'm trying to get up to speed.

**Comment by daberer** [comment]
Hi @mikahpinegar,

good question. I'm a bit unsure sure, because this has to to do with soil moisture behavior and I wasn't present when the methods were developed. I think the methods are kind of optimized for time series with hourly observations.

In case of the soil moisture spike detection (the method using this 25 hour window). My understanding was that we are looking for one timestamp events (for instance caused by a sensor malfunction).  E.g. for a single observation that is a positive or negative outlier. 

Therefore it probably would not make sense to multiply by number_of_samples_in_an_hour here but use the 12 timestamps before and after, even if the frequency is shorter than 1h. Nor adapt the shift-length.

Maybe for the other detection methods D07 (sm-drop), D08 (sm-rise), D09 (low constant values) and D10 (sm-high plateaus) it could make more sense. 

sry for not being more helpful,
Daniel
